import 'dart:async';
import 'dart:developer';
import 'dart:io';
import 'dart:math' as math;
import 'package:file_picker/file_picker.dart';
import 'package:flutter_chat_types/flutter_chat_types.dart' as types;
import 'package:flutter_chat_ui/flutter_chat_ui.dart';
import 'package:apppro/feature/chat/domain/entities/chat.dart' as domain;
import 'package:dartz/dartz_unsafe.dart';
import 'package:flutter_image_compress/flutter_image_compress.dart';
import 'package:hive/hive.dart';
import 'package:apppro/feature/profile/domain/entities/staff.dart';
import 'package:apppro/feature/profile/domain/repositories/profile_provider.dart';
import 'package:apppro/shared/models/param_detail_video.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart' as provider;
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
// [FIX] Import ini penting untuk TapGestureRecognizer
import 'package:flutter/gestures.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:flutter_svg/svg.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter_riverpod/legacy.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:apppro/core/service/pref/app_preference_key.dart';
import 'package:apppro/core/service/pref/app_preference_provider.dart';
import 'package:apppro/core/utils/helper/helper.dart';
import 'package:apppro/core/utils/theme/color.dart';
import 'package:apppro/core/widgets/app_widgets.dart';
import 'package:apppro/feature/auth/domain/entities/user.dart';
import 'package:apppro/feature/chat/domain/repository/chat_provider.dart';
import 'package:apppro/feature/contact/domain/repository/contact_provider.dart';
import 'package:apppro/feature/files/domain/repository/file_collection_provider.dart';
import 'package:apppro/gen/assets.gen.dart';
import 'package:apppro/routes.dart';
import 'package:apppro/shared/models/param_detail_image.dart';
import 'package:shimmer/shimmer.dart';
import 'package:uuid/uuid.dart';
import 'package:apppro/api/core/state/app_state.dart';
import 'package:skeletonizer/skeletonizer.dart';
import 'package:collection/collection.dart';
import 'package:video_player/video_player.dart';
import 'package:apppro/core/utils/theme/theme.dart';

import 'package:scroll_to_index/scroll_to_index.dart';
import 'package:flutter_sound/flutter_sound.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:dio/dio.dart';
import 'package:apppro/api/core/provider/core_provider.dart';
import 'package:apppro/api/core/api_core.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'package:apppro/feature/recorder/presentation/views/recorder.dart';
import 'package:apppro/feature/camera/presentation/views/camera_location.dart';
import 'package:apppro/feature/profile/presentation/views/staff.dart';

part 'chat_view.dart';
part '../widgets/chat_bubble_text.dart';
part '../widgets/chat_bubble_special.dart';
part '../widgets/chat_bubble_media_group.dart';
part '../widgets/chat_helpers.dart';
part '../widgets/chat_ui_components.dart';
part '../widgets/chat_content_hora.dart';
part '../widgets/chat_typing_indicator.dart';
part '../widgets/chat_swipe_to_reply.dart';

// [REFACTORED PARTS]
part '../widgets/hora_chat_input_field.dart';
part '../widgets/chat_input_recorder.dart';
part '../widgets/chat_input_attachments.dart';
part '../widgets/chat_input_preview.dart';
part '../widgets/chat_input_mention.dart';
part '../widgets/hora_chat_media_preview.dart';